@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzM4NCJ9.eyJpbWFnZSI6IjkyODkzZGUwLWI0ZWYtNGM3NS04ZjU2LTA1ZmExNzI1ZmIyOSIsImZpcnN0bmFtZSI6InVDb2RlIiwicGVybWlzc2lvbkxldmVsIjoxLCJtb2JpbGUiOiI2MDE3NjQwODI1MCIsInVzZXJJZCI6IjkyODkzZGUwLWI0ZWYtNGM3NS04ZjU2LTA1ZmExNzI1ZmIyOSIsIndlYkFjY2VzcyI6MSwiZW1haWwiOiJ0ZXN0QHVjb2RlLmFpIiwibGFzdG5hbWUiOiJUZXN0Iiwic3ViIjoidGVzdEB1Y29kZS5haSIsImlhdCI6MTY5OTg1MjI0NiwiZXhwIjoxNjk5ODY2NjQ2fQ._npQVbsK4i5bSy2xGL3NttrR_1Lf8781GU7YUrdGsFUzHdvWE7Szya8UJaQP0xEw
@TESTID = 3
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}

###
POST {{HOST}}/accesspermission HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
    "endPointname":"commodo",
    "add":false,
    "edit":false,
    "read":false,
    "delete":false,
    "username":"nur"
}

###

GET {{HOST}}/accesspermission? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/accesspermission?endPointname=commodo HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/accesspermission/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}


###
PATCH {{HOST}}/accesspermission/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"endPointname":"commodo",
"add":"false",
"edit":"false",
"read":"false",
"delete":"false",
"username":"irure"
}
###
DELETE {{HOST}}/accesspermission/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
