@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzM4NCJ9.eyJpbWFnZSI6IjkyODkzZGUwLWI0ZWYtNGM3NS04ZjU2LTA1ZmExNzI1ZmIyOSIsImZpcnN0bmFtZSI6InVDb2RlIiwicGVybWlzc2lvbkxldmVsIjoxLCJtb2JpbGUiOiI2MDE3NjQwODI1MCIsInVzZXJJZCI6IjkyODkzZGUwLWI0ZWYtNGM3NS04ZjU2LTA1ZmExNzI1ZmIyOSIsIndlYkFjY2VzcyI6MSwiZW1haWwiOiJ0ZXN0QHVjb2RlLmFpIiwibGFzdG5hbWUiOiJUZXN0Iiwic3ViIjoidGVzdEB1Y29kZS5haSIsImlhdCI6MTY5OTg0Njk4NiwiZXhwIjoxNjk5ODYxMzg2fQ.trAyZU0RpWmH7EHtAEUpWg6kuJajsgk4ifLqbY2AeCn1Fr6AWATaNcuXE2-vOoTC
@TESTID = 4
//LOGIN ENDPOINT TO GET AUTH TOKEN

POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/apiactivity HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
  "partnerId": 2,
  "apikeyID": "deserunt",
  "apicallName": "magna",
  "apicallResult": "minim",
  "errorDetails": "dolor"
}

###

GET {{HOST}}/apiactivity? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/apiactivity?partnerId=2&apikeyID=deserunt&apicallName=magna&apicallResult=minim&errorDetails=dolor HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/apiactivity/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}


###
PATCH {{HOST}}/apiactivity/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"partnerId":"1",
"aPIKeyID":"adipisicing",
"aPICallName":"magna",
"aPICallResult":"minim",
"errorDetails":"dolor"
}
###
DELETE {{HOST}}/apiactivity/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
