@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzM4NCJ9.eyJpbWFnZSI6IjU5OTZmYTkxLWFkMWItNDgzMC1hZDMxLTJmYWM3YjM5NjBhMSIsImZpcnN0bmFtZSI6IkJOUEwiLCJwZXJtaXNzaW9uTGV2ZWwiOjEsIm1vYmlsZSI6IjYwMTc2NDA4MjUwIiwidXNlcklkIjoiNTk5NmZhOTEtYWQxYi00ODMwLWFkMzEtMmZhYzdiMzk2MGExIiwid2ViQWNjZXNzIjoxLCJlbWFpbCI6Im51ckBibnBsLmNvbSIsImxhc3RuYW1lIjoiVGVzdCIsInN1YiI6Im51ckBibnBsLmNvbSIsImlhdCI6MTY5OTg0NjE4OCwiZXhwIjoxNjk5ODYwNTg4fQ.v-mMALMu9mavhb4Wz42qHb0kJJ7tV6TJjlK2RqQWF_GblVqpoCu-TfdRV-wcujP3
@TESTID = 1
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/partner HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"contactName":"nisi",
"email":"eu5545@ucode.ai9",
"phone":"6015554754075808",
"address":"Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.",
"bussinessName":"euclf",
"logo":"",
"facebook":"https://excode.net",
"instagram":"https://ucode.ai",
"twitter":"https://ucode.ai",
"whatsapp":"https://excode.net",
"youtube":"https://mypaaa.com",
"agreement":"",
"city":"officia",
"state":"inclf",
"zipcode":"1",
"commision":"1.35",
"transactionLimit":"1",
"password":"ucode1234"
}


###
#MAIN REGISTRATION for Java Spring boot
POST {{HOST}}/reg HTTP/1.1
content-type: application/json
 
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408250"
}
###

GET {{HOST}}/partner? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/partner?contactName=nisi&email=eu55@ucode.ai9&phone=60154754075808&address=Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.&bussinessName=euclf HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/partner/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}


###
PATCH {{HOST}}/partner/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"contactName":"nisi",
"email":"eu@ucode.ai9",
"phone":"601754075808",
"address":"Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.",
"bussinessName":"euclf",
"logo":"",
"facebook":"https://excode.net",
"instagram":"https://ucode.ai",
"twitter":"https://ucode.ai",
"whatsapp":"https://excode.net",
"youtube":"https://mypaaa.com",
"agreement":"",
"city":"officia",
"state":"inclf",
"zipcode":"1",
"commision":"1.35",
"limit":"1.35",
"password":"ucode1234"
}
###
DELETE {{HOST}}/partner/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
