@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzM4NCJ9.eyJpbWFnZSI6IjU5OTZmYTkxLWFkMWItNDgzMC1hZDMxLTJmYWM3YjM5NjBhMSIsImZpcnN0bmFtZSI6IkJOUEwiLCJwZXJtaXNzaW9uTGV2ZWwiOjEsIm1vYmlsZSI6IjYwMTc2NDA4MjUwIiwidXNlcklkIjoiNTk5NmZhOTEtYWQxYi00ODMwLWFkMzEtMmZhYzdiMzk2MGExIiwid2ViQWNjZXNzIjoxLCJlbWFpbCI6Im51ckBibnBsLmNvbSIsImxhc3RuYW1lIjoiVGVzdCIsInN1YiI6Im51ckBibnBsLmNvbSIsImlhdCI6MTY5OTg0NjE4OCwiZXhwIjoxNjk5ODYwNTg4fQ.v-mMALMu9mavhb4Wz42qHb0kJJ7tV6TJjlK2RqQWF_GblVqpoCu-TfdRV-wcujP3
@TESTID = 1
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/plan HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"planName":"new23",
"status":"1",
"noOfInstallment":"1",
"commision":"1.35"
}

###

GET {{HOST}}/plan? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/plan?planName=estclf&status=1&noOfInstallment=1&commision=1.35 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/plan/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}


###
PATCH {{HOST}}/plan/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"planName":"new255",
"status":"1",
"noOfInstallment":"1",
"commision":"1.35"
}
###
DELETE {{HOST}}/plan/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
