@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/apikeys HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"keyValue":"deserunt",
"permissions":"culpa",
"issueDate":"2023-12-08T09:28:27.580Z",
"expiryDate":"2023-12-08T09:28:27.580Z",
"partnerId":"1",
"status":"1"
}

###

GET {{HOST}}/apikeys? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/apikeys?keyValue=deserunt&permissions=culpa&issueDate=2023-12-08&expiryDate=2023-12-08&partnerId=1&status=1 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/apikeys/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/apikeys/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"keyValue":"deserunt",
"permissions":"culpa",
"issueDate":"2023-12-08T09:28:27.580Z",
"expiryDate":"2023-12-08T09:28:27.580Z",
"partnerId":"1",
"status":"1"
}
###
PATCH {{HOST}}/apikeys/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"keyValue":"deserunt",
"permissions":"culpa",
"issueDate":"2023-12-08T09:28:27.580Z",
"expiryDate":"2023-12-08T09:28:27.580Z",
"partnerId":"1",
"status":"1"
}
###
DELETE {{HOST}}/apikeys/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
