@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/latepayments HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"customerID":"1",
"transactionID":"1",
"latePaymentAmount":"1.35",
"latePaymentDate":"2023-12-08T09:28:28.097Z",
"partnerId":"1",
"status":"1"
}

###

GET {{HOST}}/latepayments? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/latepayments?customerID=1&transactionID=1&latePaymentAmount=1.35&latePaymentDate=2023-12-08&partnerId=1&status=1 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/latepayments/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/latepayments/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"customerID":"1",
"transactionID":"1",
"latePaymentAmount":"1.35",
"latePaymentDate":"2023-12-08T09:28:28.097Z",
"partnerId":"1",
"status":"1"
}
###
PATCH {{HOST}}/latepayments/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"customerID":"1",
"transactionID":"1",
"latePaymentAmount":"1.35",
"latePaymentDate":"2023-12-08T09:28:28.097Z",
"partnerId":"1",
"status":"1"
}
###
DELETE {{HOST}}/latepayments/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
