@HOST = http://localhost:8080
@AUTH = eyJhbGciOiJIUzM4NCJ9.eyJpbWFnZSI6Ijc5ZDg0NzM5LTZlN2MtNGQ4MS1iZDVjLWJkMGQxODI1MGE3NyIsImZpcnN0bmFtZSI6IkJOUEwiLCJwZXJtaXNzaW9uTGV2ZWwiOjEsIm1vYmlsZSI6IjYwMTc2NDA4MjUwIiwidXNlcklkIjoiNzlkODQ3MzktNmU3Yy00ZDgxLWJkNWMtYmQwZDE4MjUwYTc3Iiwid2ViQWNjZXNzIjoxLCJlbWFpbCI6ImRmZGZAYm5wbC5jb20iLCJsYXN0bmFtZSI6IlRlc3QiLCJzdWIiOiJkZmRmQGJucGwuY29tIiwiaWF0IjoxNjk5NTIyNDI1LCJleHAiOjE2OTk1MzY4MjV9.qwoXAIWqRUiHQjcwzyGSuBvKnD1CI6Jq_1hYAwa5FQ0JMnTEbUfTit24L87qCpFs
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"dfdf@bnpl.com",
"password":"123456"
}
###
POST {{HOST}}/partner HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"contactName":"nisi",
"email":"eu@ucode.ai9",
"phone":"601754075808",
"address":"Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.",
"bussinessName":"euclf",
"logo":"",
"facebook":"https://excode.net",
"instagram":"https://ucode.ai",
"twitter":"https://ucode.ai",
"whatsapp":"https://excode.net",
"youtube":"https://mypaaa.com",
"agreement":"",
"city":"officia",
"state":"inclf",
"zipcode":"1",
"commision":"1.35",
"transactionLimit":"1",
"password":"ucode1234"
}

###

#MAIN REGISTRATION for NODEJS VERSION
POST {{HOST}}/partner/reg HTTP/1.1
content-type: application/json
    
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408250"
}
###
#MAIN REGISTRATION for Java Spring boot
POST {{HOST}}/reg HTTP/1.1
content-type: application/json
 
{
"email":"test@ucode.ai",
"password":"123456",
"firstname":"uCode",
"lastname":"Test",
"usertype":"0",
"mobile":"60176408250"
}
###

GET {{HOST}}/partner? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/partner?contactName=nisi&email=eu@ucode.a&phone=6017540758&address=Non tempor&bussinessName=euclf&logo=&facebook=https://ex&instagram=https://uc&twitter=https://uc&whatsapp=https://ex&youtube=https://my&agreement=&city=officia&state=inclf&zipcode=1&commision=1.35&limit=1.35&password=ucode1234 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/partner/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/partner/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"contactName":"nisi",
"email":"eu@ucode.ai9",
"phone":"601754075808",
"address":"Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.",
"bussinessName":"euclf",
"logo":"",
"facebook":"https://excode.net",
"instagram":"https://ucode.ai",
"twitter":"https://ucode.ai",
"whatsapp":"https://excode.net",
"youtube":"https://mypaaa.com",
"agreement":"",
"city":"officia",
"state":"inclf",
"zipcode":"1",
"commision":"1.35",
"limit":"1.35",
"password":"ucode1234"
}
###
PATCH {{HOST}}/partner/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"contactName":"nisi",
"email":"eu@ucode.ai9",
"phone":"601754075808",
"address":"Non tempor labore adipisicing voluptate nisi excepteur consectetur anim in elit.",
"bussinessName":"euclf",
"logo":"",
"facebook":"https://excode.net",
"instagram":"https://ucode.ai",
"twitter":"https://ucode.ai",
"whatsapp":"https://excode.net",
"youtube":"https://mypaaa.com",
"agreement":"",
"city":"officia",
"state":"inclf",
"zipcode":"1",
"commision":"1.35",
"limit":"1.35",
"password":"ucode1234"
}
###
DELETE {{HOST}}/partner/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
