@HOST = http://localhost:8080
@AUTH = authtoken
@TESTID = testID
//LOGIN ENDPOINT TO GET AUTH TOKEN
POST {{HOST}}/auth HTTP/1.1
content-type: application/json

{
"email":"test@ucode.ai",
"password":"123456"
}
###
POST {{HOST}}/refunds HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"transactionID":"exclf",
"refundAmount":"1.35",
"reason":"Dolore elit sit eiusmod enim magna pariatur.",
"refundDate":"2023-12-08T09:28:27.060Z",
"partnerId":"1",
"status":"1",
"customerId":"1"
}

###

GET {{HOST}}/refunds? HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/refunds?transactionID=exclf&refundAmount=1.35&reason=Dolore eli&refundDate=2023-12-08&partnerId=1&status=1&customerId=1 HTTP/1.1
Authorization: Bearer {{AUTH}}

###
GET {{HOST}}/refunds/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}

###
PUT {{HOST}}/refunds/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"transactionID":"exclf",
"refundAmount":"1.35",
"reason":"Dolore elit sit eiusmod enim magna pariatur.",
"refundDate":"2023-12-08T09:28:27.060Z",
"partnerId":"1",
"status":"1",
"customerId":"1"
}
###
PATCH {{HOST}}/refunds/{{TESTID}} HTTP/1.1
Authorization: Bearer {{AUTH}}
content-type: application/json

{
"transactionID":"exclf",
"refundAmount":"1.35",
"reason":"Dolore elit sit eiusmod enim magna pariatur.",
"refundDate":"2023-12-08T09:28:27.060Z",
"partnerId":"1",
"status":"1",
"customerId":"1"
}
###
DELETE {{HOST}}/refunds/{{TESTID}} http/1.1
Authorization: Bearer {{AUTH}} 
