spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: SETTLEMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/bnpl_settlement
    username: root
    password: admin008
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200KB
      max-request-size: 1000KB
  main:
    allow-bean-definition-overriding: true
    lazy-initialization: true

server:
  error:
    include-message: always
  port: 8082

eureka:
 instance:
   prefer-ip-address: true
 client:
   fetch-registry: true
   register-with-eureka: true
   service-url:
     defaultZone: http://localhost:8761/eureka
